# Generated by Django 4.0.4 on 2022-05-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
