# Generated by Django 4.0.4 on 2022-05-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
